### ISSUE TITLE
A mistake in page 18 of whitepaper_TI_SILABS_BLE_RCEs_v1.0.1.pdf

### ISSUE THREAD

**Issue by dingiso** [darkmentorllc/publications#1]
Hi darkmentorllc,

I noticed an error in the page 18 of "whitepaper_TI_SILABS_BLE_RCEs_v1.0.1.pdf". There's a mistake in the following sentence:

```
Based on Cortex-M3 (the target board’s MCU) calling convention, R0, R1, and R3 are dest, src, and n
respectively.
```

The correction should be that 'n' is stored in R2, not R3. Your subsequent explanation in the document correctly describes this convention.

Thanks,
Dingisoul

**Comment by darkmentorllc** [comment]
Thank you for letting us know. I've corrected the typo.
